# Generated by Django 3.0.14 on 2022-11-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': '상품', 'verbose_name_plural': '상품'},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=1, max_length=30, verbose_name='카테고리'),
            preserve_default=False,
        ),
    ]
