# Generated by Django 4.1.3 on 2022-11-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0002_alter_image_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.FileField(upload_to="images/women_top_reference_person_test/"),
        ),
    ]
