# Generated by Django 4.1.3 on 2022-11-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0003_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                upload_to="images/women_top_reference_person_test/"
            ),
        ),
    ]
