# Generated by Django 3.0.14 on 2022-11-08 10:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_auto_20221103_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='수량')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='주문시간')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '장바구니',
                'verbose_name_plural': '장바구니',
                'db_table': 'shopping_order',
                'ordering': ['id'],
            },
        ),
    ]
