# Generated by Django 3.0.14 on 2022-11-18 09:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20221118_1845'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Shoppingcart',
        ),
    ]
